pluginManagement {
    repositories {
        maven { url = uri("https://maven.fabricmc.net/") }
        maven { url = uri("https://maven.architectury.dev/") }
        maven { url = uri("https://files.minecraftforge.net/maven/") }
        gradlePluginPortal()
    }
}


File indexProps = new File("${rootDir}/property_variants/${mc_build}.properties")
println indexProps.path
Properties properties = new Properties()
properties.load(indexProps.newDataInputStream())
def enabled=properties.getProperty("enabled_platforms")
println enabled

include("common")
include("forge")

rootProject.name = 'flowing_fluids'


