import org.gradle.jvm.tasks.Jar

architectury {
    common("forge")
}

repositories{

    maven { url = "https://api.modrinth.com/maven" }
}

dependencies {
    compileOnly("org.spongepowered:mixin:0.8.5")
    compileOnly("io.github.llamalad7:mixinextras-common:0.4.1")

    modCompileOnly("maven.modrinth:sodium:${project.sodium_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.10.2")
    testImplementation("org.mockito:mockito-junit-jupiter:5.11.0")

}
loom {
    accessWidenerPath = file("src/main/resources/flowing_fluids_${project.mc_build}.accesswidener")
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

tasks.withType(Jar).configureEach {
    exclude("net/fabricmc/api/**")
}