architectury {
    common("forge")
}

repositories{

    maven { url = "https://api.modrinth.com/maven" }
}

dependencies {
    compileOnly("org.spongepowered:mixin:0.8.5")
    compileOnly("io.github.llamalad7:mixinextras-common:0.4.1")

    modCompileOnly("maven.modrinth:sodium:${project.sodium_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    testAnnotationProcessor 'systems.manifold:manifold-preprocessor:2025.1.16'
    testCompileOnly 'systems.manifold:manifold-preprocessor:2025.1.16'

    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.10.2")
}
loom {
    accessWidenerPath = file("src/main/resources/flowing_fluids_${project.mc_build}.accesswidener")
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}